### ISSUE TITLE
GOTO definition not working for some macros

### ISSUE THREAD

**Issue by DonDi94** [erlang-ls/erlang_ls#1052]
**Describe the bug**
There are some corner cases in which the goto definition does not work for some macros:
- if ?MODULE is used as record name
- if a macro is used to define a case clause

**To Reproduce**
To reproduce, create two files:

test.erl
```erlang
-module(test).
-export([test_function/0, test_function_2/0]).
-include("export.hrl").

-define(macro, 1).

-record(?MODULE, {
    test :: #test_record{} %% GOTO Def Works
}).

-define(CASE(A, B), 
    V when V == A -> B).

test_function() -> 
    #?MODULE{}, %% GOTO Def Doesn't work
    ?macro, %% GOTO Def Works
    #test_record{}, %% GOTO Def Works
    ok. 

test_function_2() ->
    ?macro, %% GOTO Def doesn't work
    case 4 of
        ?CASE(4,5); %% GOTO Def doesn't work
        _ -> 3
    end.
```
and export.hrl
```erlang
-record(test_record, {value}).
```

**Expected behavior**
GOTO definition should bring the cursor to the macro definitions.

**Actual behavior**
- Using GOTO Def on ?MODULE does not work at all
- If a case clause is defined with a macro like ?CASE(4,5), GOTO Def will not work anywhere in the function where ?CASE(4,5) is used

**Context**
 - `erlang_ls` version (tag/sha): 0.0.27
 - Editor used: VS Code
 - LSP client used: VS Code integrated LSP

**Comment by robertoaloi** [comment]
Hi @DonDi94 and thanks for reporting!

Record names are indeed expected to be atoms by `els_parser`. In #1053 I'm attempting at adding a special case for the `?MODULE` macro, since we use the same approach in many other places due to how common the macro is. A more generic approach would be trickier.

Regarding the `CASE` macro, I believe this falls more into `erlfmt` territory. See #993 for a similar issue. Pinging @gomoripeti and @michalmuskala in case they have additional thoughts about this.

**Comment by gomoripeti** [comment]
as Roberto mentioned erlang_ls currently cannot parse the whole `test_function_2` function (because erlang_ls does not do macro resolution), so almost nothing within that function will work (including goto definition of macros). A possible solution could be to support unparseable code to some degree (https://github.com/erlang-ls/erlang_ls/issues/1037). Supporting macros and variables would be the easiest to start with. (But then the experience would be asymmetric, why goto-definition works for macros and not for functions)

**Comment by michalmuskala** [comment]
We should be able to support using macros like that inside of `case` fairly easily. Supporting the `-define` syntax for them might be much more challenging, though

**Comment by DonDi94** [comment]
Sorry for the late replay, thank you for the responses! It's a very minor bug, and it's far from breaking, but I wanted to report it anyway :)
