### ISSUE TITLE
using the add'_' to Variable causes duplication of the clause

### ISSUE THREAD

**Issue by TheGeorge** [erlang-ls/erlang_ls#1082]
**Describe the bug**
```
some(Variable) -> ok.
```
 and using the code action on Variable resutls in 
```
some(_Variable) -> ok.
some(Variable) -> ok.
```
 instead of just 
```
some(_Variable) -> ok.
```

**Context**
 - `erlang_ls` version (tag/sha):  0.18.0
 - Editor used: VSCode

**Comment by robertoaloi** [comment]
@TheGeorge I cannot reproduce this with the latest `HEAD`. Tried both Emacs and VS Code. Do you mind adding a test case showing this issue? Maybe it's a corner case which only gets triggered under certain conditions?

**Comment by robertoaloi** [comment]
Ping @TheGeorge

**Comment by TheGeorge** [comment]
I totally missed this, let me check if this is still broken

**Comment by sopotc** [comment]
> I totally missed this, let me check if this is still broken

It was broken as of yesterday.

**Comment by AminArria** [comment]
@robertoaloi  This reproduces the error for me

```erlang
-module(unused).

-export[hello/1].

hello() ->
  Wow = 8,
  "Hello World".
```
I'm using latest `HEAD`  and VS Code

From what I can tell the issue might be related to the range, in my case the start and end line received by `els_code_action_provider:handle_request` are the same (`5`) so according to a note in `replace_lines_action` that would add the line instead of replacing it.

I tested modifying the generated command to have `EndLine+1` and it solved the issue, but wondering why you couldn't replicate it and if there is something else going on

**Comment by eproxus** [comment]
Can confirm in Sublime Text 4 (4127) and Sublime LSP v1.15.0.

**Comment by plux** [comment]
Fixed
