### ISSUE TITLE
Auto-complete for atom names

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#110]

**Comment by jfacorro** [comment]
Implementing auto-completion for atom names produces a lot of noise in the options that are being auto-completed. This is because when we fold over the syntax tree, even the nodes of type `atom` that are part of other bigger nodes get added as an `atom` POI.

I will explore a little bit more to maybe find a way around so that for certain types of nodes the folding doesn't go deeper. But if this is not straight-forward I'm not sure if we want to include all atoms defined in the module and included files as completion items.

I'm open to suggestions.

**Comment by robertoaloi** [comment]
I'm fine with discarding this issue right now.

**Comment by michalmuskala** [comment]
Isn't to some extent this the same as completing module names?

**Comment by jfacorro** [comment]
> Isn't to some extent this the same as completing module names?

Conceptually it's the same, it's just getting the name of each atom from it's syntax tree node. But the way we are currently traversing the tree is by using `erl_syntax_lib:fold/3`, which goes through all nodes and provides no possibiility of filtering nodes. 

This means that for an expression such as this `lists:map(fun foo:bar/1, baz(auto_complete_only_me)).` we would get absolutely all atoms there (i.e. `lists`, `map`, `foo`, `bar`, ...) but IMO we only want `auto_complete_only_me`.
