### ISSUE TITLE
rename is not working

### ISSUE THREAD

**Issue by ivano9** [erlang-ls/erlang_ls#1270]
**Describe the bug**
When try to rename a function or wathever using the erlang_ls, just show the message that the "method is not implemented".
For this, i tested it with the minimal_lsp config to work.
https://github.com/lunarvim/lunarvim/blob/5d08a337faa798b67611a1bba545ff5116579da4/tests/minimal_lsp.lua#L1

**To Reproduce**
Put cursor over name of a function
hit: space -> l -> r

**Expected behavior**
Give me an input for introduce the new name of the function and then after press enter the editor change the old name to the new name of function over all file.

**Actual behavior**
Show in the status bar:
Output: LSP[erlangls][Info] Method not implemented: textDocument/prepareRename

**Context**
 - `erlang_ls` version (tag/sha): 0.28.0
 - Editor used: neovim
 - LSP client used: nvim-lspconfig

Lsp Log:
https://gist.github.com/ivano9/c721ad40b3df29b5c70aefe153f63dc9

**Comment by robertoaloi** [comment]
Hi @ivano9 and thanks for the report. The `prepareRename` method is definitely not implemented, but the server doesn't advertise [prepareSupport](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#renameOptions). I can double check if we're doing something wrong on our side, but it may be worth to also check with the LSP client if they're sending `prepareRename` requests disregarding the server capabilities.

**Comment by ivano9** [comment]
Hi, I see both rename and prepareRename check it
https://github.com/neovim/neovim/blob/245858460f4c7f059333e29a251abee7c675de64/runtime/lua/vim/lsp.lua#L34

Also, I have left the log above showing that it calls prepareRename.

**Comment by robertoaloi** [comment]
Yes, I read that in the logs. To clarify what I meant, what Erlang LS advertises for the `renameProvider` is:

https://github.com/erlang-ls/erlang_ls/blob/main/apps/els_lsp/src/els_general_provider.erl#L139-L140

So, essentially:

    renameProvider: true

I would expect (and that seems to happen in both Emacs and VS Code) the client to assume there's no support for `prepareRename` (otherwise we would have sent `renameProvider:  {prepareProvider: true}`).

Maybe I'm misinterpreting the specs, but it feels like the Neovim client is sending the `prepareRename` request when it shouldn't, that's why I suggested to also check on the client side.

@alanz Do you know this from the Haskell LS side?

**Comment by alanz** [comment]
> @alanz Do you know this from the Haskell LS side?

I don't, but if it is supposed to be enabled via a capability then I agree the client is erroneous

**Comment by ivano9** [comment]
Should be fixed with https://github.com/neovim/neovim/pull/18441

**Comment by robertoaloi** [comment]
Great! I will close this now, feel free to reopen if you believe there's still a server-side issue.
