### ISSUE TITLE
Code Formatting / Pretty Printing

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#15]
It should be possible to format entire Erlang modules or given portions of code via the Erlang Language Server.

Several tools and APIs exist in the Erlang / Elixir ecosystem that should be considered, either for inspiration or as libraries. For example:

* `erl_tidy` (which seems to use `erl_prettypr`
* `Code.format_string` (Elixir)
* [erl_pp](https://github.com/erlang/otp/blob/master/lib/stdlib/src/erl_pp.erl)
* [erl_prettypr](http://erlang.org/doc/man/erl_prettypr.html)
* [io_lib_pretty](https://github.com/erlang/otp/blob/master/lib/stdlib/src/io_lib_pretty.erl) (apparently used by EDTS)
* [prettypr](http://erlang.org/doc/man/prettypr.html)

Ideally, some customizations should be possible. For example, one may prefer spaces over tabs or viceversa. Some organizations use a comma-first convention, whilst others don't.

Something that should also be investigated is how to treat code that does not compile (since some of the above tools work directly on the `.beam` files).

Useful References:
* The "Programming Elixir" book should have a section about pretty-printing
* [This talk](https://www.youtube.com/watch?v=x2ckfhqB9nA) by Jose Valim covers the code formatter in Elixir
* In ["The design of a pretty-print library"](http://belle.sourceforge.net/doc/hughes95design.pdf) John Hughes introduces an algebraic approach to pretty printing
* [This](https://github.com/fireflyc/erlang-vscode/commit/14f3a14af55258b9de83f7690b688cef063f97e2?diff=split
) is the PR where formatting has been included in `erlang-vscode`
* A [Medium Post](https://medium.com/blackode/code-formatter-the-big-feature-in-elixir-v1-6-0-f6572061a4ba) discussing the code formatter in Elixir 1.6.0
* The ["Strictly Pretty"](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.34.2200) paper about pretty-printing
* [Demo usages](https://github.com/erlang/otp/blob/d6285b0a347b9489ce939511ee9a979acd868f71/lib/syntax_tools/examples/demo.erl) of the Erlang Syntax Tools libraries for pretty-printing

Useful snippets:
```erlang
c(test, [debug_info]).
{ok,{_,[{abstract_code,{_,AC}}]}} = beam_lib:chunks("test.beam",[abstract_code]),
io:put_chars(erl_prettypr:format(erl_syntax:form_list(AC))).
```

```
print(SyntaxTree, Paper, Ribbon) ->
    io:put_chars(erl_prettypr:format(SyntaxTree, [{paper, Paper},
						  {ribbon, Ribbon}])).
```

```
read(Name) ->
    {ok, Forms} = epp:parse_file(Name, [], []),
    Comments = erl_comment_scan:file(Name),
    erl_recomment:recomment_forms(Forms, Comments).
```

**Comment by tsloughter** [comment]
This is a copy of erl_tidy from OTP plus a rebar3 plugin https://github.com/tsloughter/erl_tidy/

The reason it was pulled to its own repo instead of having the plugin simply use the existing OTP erl_tidy was for faster iteration at first and then to send upstream. But I never got around to working on it, though some others have contributed.

**Comment by michalmuskala** [comment]
I'm working right now on a standalone code formatter for erlang. It's not done yet, but the goal is to have it ready & in public before Code BEAM SF. The general plan is to provide an escript, but having an Erlang API shouldn't be too hard, if needed.

`erl_tidy` unfortunately deals rather poorly with macros (`?assertMatch` from stdlib breaks it completely) and entirely disregards original formatting, which is especially painful in literals (e.g. turning binary data as in `"\x01\x56\xa6"` into unreadable `"\001V¦"` and similar). It also makes, in my opinion, many weird formatting choices that often look rather bad. It uses `erl_prettypr` underneath, which in turn uses `prettypr`, so those are mostly the same.

One issue though, is that one of the goals of the project is to have a formatter with as little knobs and options as possible, so it doesn't fit exactly in the description you provided. I'll see how far this can be pushed in practice.

**Comment by elbrujohalcon** [comment]
We (as in @AdRoll) are also working on a standalone code formatter for Erlang.
In our case, we're _loosely_ basing it on the tools already provided by OTP (like `epp_dodger` and `erl_prettypr`), but we're _forking_ them on our own project since their extensibility and personalization possibilities are limited at best.
We already made this rebar3 plugin open-source. You can find it in hex: https://hex.pm/packages/rebar3_format
It does work (in the sense that it formats your code consistently and the code it generates compiles and works just like its input), but the resulting code is not _pretty_ and there are still some bugs we need to fix (check https://github.com/Adroll/rebar3_format/issues).
Our plan is to have a presentable version for FOSDEM 2020, but we already accept contributions in the form of bug reports, feature requests and, _of course_, PRs!!

**Comment by robertoaloi** [comment]
@elbrujohalcon This is nice to know. I guess we will try to incorporate one of the formatters in the language server at some point, since it does not make sense to roll out our own if something already exists. Thanks for the pointers!

**Comment by alanz** [comment]
I am going to start on the server implementation for a formatter, to get the architecture in place.

In time we can make it pluggable / configurable, I think a lot of places will feel very strongly about what exactly gets used here, we need to be able to offer that.

**Comment by robertoaloi** [comment]
Also @elbrujohalcon why binding the formatter to `rebar3`? Wouldn't it be nicer to actually have the formatter as a standalone library and a simple rebar3 plugin to interact with it?

**Comment by elbrujohalcon** [comment]
@robertoaloi well… it's because what we _really_ wanted was to integrate the formatter with the rest of the _default_ infrastructure. In the same way that for elixir you have `mix format`, we wanted to have `rebar3 format` for Erlang.
In code, it's not hard to split the parts. You can check the repository: from `rebar3_formatter` and on, there is no rebar3-linking whatsoever, so you can just take that module and its friends and put it in a different app. But we prefer not to maintain 2 repos instead of one, if there is no real need for it.
On the other hand, if @michalmuskala's tool is eventually nicer than our `rebar3_formatter` we might end up replacing `rebar3_formatter` and friends by it and our repo will be just a small plugin on top of his lib.
But for now, at least until version 1.0.0 of our project, we'll keep it as a single repo with properly compartimentalized code in it.

**Comment by robertoaloi** [comment]
@elbrujohalcon I guess it's the usual pros and cons of having a single repo vs having multiple ones. But let's see how things will evolve. It was more a curiosity than anything else.

**Comment by robertoaloi** [comment]
Related discussion on the erlang/otp repo: https://github.com/erlang/otp/pull/2451

**Comment by matyasmarkovics** [comment]
Hi @robertoaloi, I've just learned you're working on this project via Linkedin and found through your Medium blog that you're looking at formatters.

I was bold (as I am) enough to start a pet Project rewriting/refactoring `erl_prettypr.erl`. I thought I'd share the code and see if there's interest in that approach: https://github.com/matyasmarkovics/otp/blob/erl_prettypr/lib/syntax_tools/src/erl_prettypr.erl

Unfortunately there's no docs or thorough tests available at the moments, so there's still a lot of work remaining.

The initial idea was to "fix" the `erl_prettypr.erl` module to produce a sensible output. However, I've found it difficult to improve and make it configurable, so I've decided to simplify it first.

There are a lot of similarities between Erlang statements, like `case-clauses` and `function-clauses`, or between data-structure like  `lists`, `tuples` and `binaries`, so I've tried to collapse these cases into one, so that they have the same layout.

The produced code-layout relies on what's possible with the `prettypr` built into OTP, which has only 4 different layouts: `sep/1`, `par/1`, `above/2` and `beside/2`. However, these are surprisingly versatile.

My goal is to make the layout configurable, by expending on the `#ctxt.formatter`, so that any of these lines can be effectively altered: https://github.com/matyasmarkovics/otp/blob/erl_prettypr/lib/syntax_tools/src/erl_prettypr.erl#L134-L189

Solving the leading-comma would be simple by providing an alternative implementation of the sequencing-jointer: https://github.com/matyasmarkovics/otp/blob/erl_prettypr/lib/syntax_tools/src/erl_prettypr.erl#L1662 - As with the `formatter` this would have to be done on a per statement basis.

Finally, there should be some presets with sensible layouts for those who just want it to work.

I've tested it only manually so far with 1 fairly complex module from work, so very much alpha-state.

**Comment by elbrujohalcon** [comment]
@matyasmarkovics we've been through that while working on the creation of [rebar3_format](https://github.com/AdRoll/rebar3_format) and after a lot of time invested fighting against `erl_prettypr` we left our version of it (called `otp_formatter`) in its own module, and created our own [`default_formatter`](https://github.com/AdRoll/rebar3_format/blob/master/src/default_formatter.erl) based on it.
On one hand, what I am saying is _you're not alone_, not by any means.
On the other hand, maybe… you want to consider contributing to our repo, too 🙏

**Comment by robertoaloi** [comment]
Hi @matyasmarkovics!

Yes, there's currently a little explosion in terms of Erlang formatters nowadays (finally!). From an Erlang LS perspective, we are very happy to use external libraries that provide formatting functionalities (and maybe support multiple ones, in case people want to choose).

Right now we are integrating with `rebar3_format` that @elbrujohalcon mentioned (looking forward to a comma-first version of it!), but we're also keeping an eye on @michalmuskala 's work at WhatsApp. In your case, would it make sense to incorporate those changes in OTP's `erl_prettypr`?

I would really love to hear @richcarl opinion on the current formatting scene...

**Comment by richcarl** [comment]
@robertoaloi At the moment, my hopes are highest for the implementation by @michalmuskala which is based on a more modern version of the prettyprinting layout engine. We intend to make this public as soon as possible.

**Comment by michalmuskala** [comment]
Working on the formatter, my view is that the actual complexity lies in the frontend of the formatter - the parsing of the Erlang code. The backend - pretty-printing and formatting algorithm present challenges of their own, but those are known challenges faced by other languages as well. 

Without changes to the parser there is a lot of things that can't be handled correctly - for example `[1]` and `[1 | []]` having the same AST or `"\x97" "b"` collapsed to `"ab"` with no way to recover the original formatting (there are many, many more cases of things like that). Not to mention macros - `epp_dodger` in my measurements failed on around 20% of our internal codebase and the results were even worse for OTP that contains a lot of "interesting" macros.

**Comment by elbrujohalcon** [comment]
For `rebar3_format` we decided that turning `[1 | []]` into `[1]` was a totally valid thing for the formatter to do. The formatter _knows_ the best way to write list literals with one element (or multiple elements).
Something similar happens with strings, if you really want them separated you can always write `"\x97" ++ "b"` or  `[$\x97 | "b"]`.
And about macros… `ktn_dodger` does a slightly better job at handling them than `epp_dodger`, but yeah… there is still a lot of work to do there.
