### ISSUE TITLE
Include link to OTP documentation on hover

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#154]
When hovering  on OTP library functions, a link to the relevant official OTP documentation page should be included at the bottom of the type specs / edoc.

The location of the documentation should be configurable (local man pages, local html pages) and maybe default to remote OTP pages.

**Comment by robertoaloi** [comment]
@dgud What do you think about having this as a fallback in the case a user is using OTP < 23 ? Relates to #174

**Comment by dgud** [comment]
This sounds good to me, but for me the emacs html rendering and usage is still to bad, I have tried to use it with the already available 'erldoc.el' but I couldn't make anchors work in emacs-25 with the builtin browser.

 #174 might be a bit much work when in a year everybody will be on 23
( except you guys :-)

**Comment by alanz** [comment]
@dgud 
> but for me the emacs html rendering and usage is still to bad
What version of emacs are you running?  Are you running it in a terminal, or as a gui?

**Comment by dgud** [comment]
I have used emacs25 in a gui, i.e. X-window or the gui variant on windows, 
now I run emacs26 (since there are markdown rendering problems in 25) 
have not tested html handling with that version.

**Comment by alanz** [comment]
@dgud I think the markdown stuff in the gui needs emacs 26, which I am running (on debian and mac) and it works for me.

**Comment by dgud** [comment]
I understand that but I'm afraid that it will lead to a bad first impressions.
Ubuntu LTS (i.e. currently 18.04) which is what most linux users use (at least on Ericsson)
have only emacs25 as a package.

Now I'm working from home (for other reasons) using windows and WSL which uses ubuntu 18.04 so first thing I had todo was to fix emacs26.

Now Ubuntu 20.04 should be ready soon and I guess that will have emacs26 so I guess that problem is soon solved.

**Comment by robertoaloi** [comment]
Emacs 27 is almost out btw :)
