### ISSUE TITLE
Generic LS implementation

### ISSUE THREAD

**Issue by vladdu** [erlang-ls/erlang_ls#2]
This is a simple server that just translates JSON-RPC to calls to Erlang library functions, keeping track of the ongoing requests.

- transport should be configurable (at least TCP and stdio, as they are what's used currently) 
- define naming of the library callbacks implementing the LSP methods 
- should the method parameters and results be translated to/from Erlang terms independent of the LSP format? That's maybe an internal detail.
- handle cancellable requests; optionally, be able to return partial results.

**Comment by robertoaloi** [comment]
I am closing this issue since not really actionable. These are all valid points of discussions, but they should be addressed separately. Specifically:

* A new issue should be created to make the transport configurable
* Naming can be discussed as part of other PRs rather than as an isolated issue
* The third one could be ignored for now
* A new issue should be created for handling "cancellable requests"
