### ISSUE TITLE
Fork the epp_dodger module

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#235]
Having a fork of the epp_dodger will allow us to:

* Hook into the internal parser, to avoid the double pass in `els_parser`
* Edit the dodger to operate on text, rather than on binaries
* Avoid the `apply` in `els_parser` due to Dialyzer spec issues

**Comment by jfacorro** [comment]
The underlying reason why `epp_dodger` expects an IO device is because it is using `io:scan_erl_form/3`. If we use something similar to [`StringIO`](https://hexdocs.pm/elixir/StringIO.html) or [`StringReader`](https://github.com/clojerl/clojerl/blob/master/src/erl/erlang/erlang.io.StringReader.erl), which wrap a binary or string in an IO device, then it will "just work".

**Comment by michalmuskala** [comment]
What is the reason for using `epp_dodger` instead of regular `epp`? The main difference is not expanding macros and not handling include files - I would assume for indexing one would want macros to be actually expanded and includes resolved, right? Otherwise the indexing information could be incomplete, for example with something like `-module(?NAME_BEHIND_MACRO)` which is, unfortunately, fairly common in OTP itself and in some projects in the wild as well.

**Comment by robertoaloi** [comment]
There are a few reasons. For example:

* Be able to find the definition of a macro
* Be able to find all references to a macro
* Be able to navigate "inside" an include/include_lib

Also, it enables code navigation in case of conditional compilation.

**Comment by robertoaloi** [comment]
Out of curiosity, could you point to where OTP makes use of macros as module names?

**Comment by michalmuskala** [comment]
That definitely makes sense. I guess it's a compromise. 

For example [hipe_x86_main](https://github.com/erlang/otp/blob/master/lib/hipe/x86/hipe_x86_main.erl) and a lot of other modules/module templates inside HiPE and related things. Some other places too.

From some other weird macro things I discovered in the wild (I don't think it's in OTP itself, but I didn't check) was defining functions with macros at least in two different ways:
```erl
-define(FUN_NAME, foo).
?FUN_NAME(Args, ...) -> ...

-define(FUN_BODY(Name, ...), Name() -> ...).
?FUN_BODY(foo, ...).
```
And lots of other "fun" uses of macros. The formatter I mentioned in the other issue includes a parser that can deal with those except for some craziest things and makes macros first-class AST nodes. The interface is the same as `erl_parse`, so it should be fairly easy to integrate, if desired once it's published.
