### ISSUE TITLE
Rebar3 release project are not properly indexed

### ISSUE THREAD

**Issue by hommeabeil** [erlang-ls/erlang_ls#274]
**Describe the bug**
Creating a rebar3 release project (rebar3 new release) does not get indexed. On this king of project, the server do not seems to be able to manage a simple find go to.

**To Reproduce**
1. Install lsp-mode for emacs with spacemacs
2. Create a release project with `rebar3 new release my_release`
3. Open the rebar.config and ensure `erlang-mode` is enable. This will enable the the lsp as well.
4. Open the file `apps/my_release/my_release_app.erl`
5. Try to `,gg` to your root supervisor.
6. You should get a no match found.
7. Visit the supervisor file and return to the app file.
8. Now the goto will work

**Expected behavior**
The goto should work when visiting the app file the first time.

**Actual behavior**
The file in a release project does not get indexed.

**Context**
 - `erlang_ls` version (tag/sha): daa347c6578825d691d185edceb951dc999a7b96
 - Editor used: emacs/spacemacs (dev, 8fcc9d849044dca6e69ff3f7bda89f82abf848b7)
 - LSP client used: lsp-mode

**Comment by jfacorro** [comment]
This is because `erlang_ls` currently assumes the `src`, `test` and `include` directories are in the  root  folder. We have #6 to add support for `rebar3`  projects, but something more  general would be to be able to provide an `apps_dirs` configuration value.

In the `erlang_ls.config` you would be able to provide a list of directories (or a path using globs) that would be the root directory to all applications in the projects. For this it would be:

```
apps_dirs:
  - "app/*"
``` 

The default value would just be a single directory, the current one.

@robertoaloi WDTY?

**Comment by robertoaloi** [comment]
It sounds like a good idea. And it will simplify the implementation of #6 later on.

@hommeabeil Thanks for reporting.

**Comment by michalmuskala** [comment]
I guess another option to automate this could be to discover all the directories recursively that have a `rebar.config` file and a `src` directory. This should cover most use-cases when using rebar - it discovers single-app projects easily and also umbrellas, where it skips the root project (since it wouldn't have a `src` directory).
