### ISSUE TITLE
Stop database properly

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#337]
Not stopping the Erlang node properly will cause un-necessary table reparations on start, which can result in long "wait for tables" times.

**Comment by jfacorro** [comment]
Related Stack Overflow Q&A: [How to ensure fast startup times of mnesia](https://stackoverflow.com/questions/395433/how-to-ensure-fast-startup-times-of-mnesia).

**Comment by jfacorro** [comment]
There is a bug that might be related to this issue.

When starting from a clean DB listing all references for a function works as expected. But after restarting the server and loading the DB, the list of references is missing all items except the usages from the same module. This could be because the DB didn't have the time to close correctly.
