### ISSUE TITLE
Correctly handle RootUri during initialization

### ISSUE THREAD

**Issue by robertoaloi** [erlang-ls/erlang_ls#400]
**Describe the bug**

According to the LSP protocol, if no folders are open, the `rootUri` parameter during initialization should be set to `null`. Whilst most editors always set the proper `rootUri` (e.g. Emacs does it via _projectile_),  Sublime Text 3 (aka ST3) editor does not. If `null` is sent to the server, the server does not respond to the initialization message.

**To Reproduce**
Open a `.erl` file in a newly configured Sublime editor.

**Context**
 - `erlang_ls` version (tag/sha): latest
 - Editor used: ST3
 - LSP client used: LSP

**Notes**
We should also log the initialization message from the server side.

**Comment by alanz** [comment]
What should the behaviour be?

I would propose  separating initialisation into two parts, one which just acks the message, and another which kicks off indexing, set the various paths, loading config files and the rest, which we trigger as soon as we get a URI. 

The problem with that is that the server is then required to have project root determination logic, based on the URI of the first file it is asked to open.

**Comment by alanz** [comment]
And [this](https://github.com/microsoft/language-server-protocol/issues/176#issuecomment-278296141) comment may be relevant

> The root Uri basically determines the workspace you have open. In 99% of the cases documents will be inside that workspace but there is no enforcement of this and a language server should handle documents outside the root gracefully. All language servers developed by the VS Code team do so. If we receive a document (for example a json file) from outside the workspace we still provide basic language features for them but can't respect any workspace specific setting since we can't load any.

> At the end it is up to the implementer of the LS to handle this correctly.

**Comment by jfacorro** [comment]
> I would propose separating initialisation into two parts, one which just acks the message, and another which kicks off indexing, set the various paths, loading config files and the rest, which we trigger as soon as we get a URI.
> 
> The problem with that is that the server is then required to have project root determination logic, based on the URI of the first file it is asked to open.

I like this approach but I fear that things will get too complex, because:
1.  As you mention, we would need to implement the logic to determine what is the root URI based on the first file URI we get. The result might be surprising to the user.
2. Until we have a rootURI we don't create the DB and without the DB we fail to provide any functionality.

The alternative approach I was thinking about to support a `null` value for `rootUri` on initializationa are the following:

1.  Use the current working directory (i.e. `file:get_cwd/0`) from where the `erlang_ls` escript is started.
2. Use a temporary directory (e.g. under `/tmp` in *nix).
3. Change the code to not assume there is a `rootUri`. This would result in a "generic" DB created for the `rootUri`-less files. And any file that is opened without a `rootUri` would end up in this "project". This would also result in a set of configuration values that don't apply anymore, which would probably trigger other changes in the code where the assumption is that there is a `rootUri`.

The disadvantage of 1 and 3 is that we would rely on the fact that only one editor is opening all  `rootUri`-less files. If this is not the case a second editor would spawn a new instance of erlang_ls and try to use the `rootUri`-less DB.

The nice thing about 2 is that what's described above doesn't happen and the DB's get deleted when they are no longer used.

**Comment by jfacorro** [comment]
The approach taken in #584 seems to be good enough. We can revisit this in the future if other issues come up.
