### ISSUE TITLE
erlang_ls language server integration with theia IDE

### ISSUE THREAD

**Issue by ramagandi** [erlang-ls/erlang_ls#470]
Hi,

I would like to integrate erlang_ls language server with theia IDE. is there any process exists for the same?. Please provide inputs.
Thanks in advance.

**Comment by gilbertwong96** [comment]
THEIA is based on visual studio code, it should be no problem  to integrate erlang_ls with theia IDE

Gilbert Wong

**Comment by jfacorro** [comment]
@ramagandi As @gilbertwong96 say the Erlang LS VS Code extension can be downloaded from the marketplace [here](https://marketplace.visualstudio.com/items?itemName=erlang-ls.erlang-ls) (see the "Download Extension" link), and installed in your Theia IDE instance without any issues. 

The environment were you are running Theia will need to have Erlang/OTP installed so that the Erlang LS server can be started. For a pointer on how to start Theia IDE on Gitpod please check this [thread](https://github.com/gitpod-io/gitpod/issues/30).

**Comment by jfacorro** [comment]
@ramagandi As an example, adding the following content in a `.gitpod.yml` file in your github/gitlab repository gives you a working environment with Erlang LS installed and working:
```
image: erlang:22.2.7

vscode:
  extensions:
    - erlang-ls.erlang-ls@0.0.8
```

**Comment by ramagandi** [comment]
> THEIA is based on visual studio code, it should be no problem  to integrate erlang_ls with theia IDE Gilbert Wong
> […](#)
> On Feb 25, 2020, 18:09 +0800, erlang-ls/erlang_ls ***@***.***>, wrote: theia IDE



I would like to integrate erlang_ls in linux environment not in Desktop environment. How can we download from marketplace and integrate in theia linux environment.
Thanks in advance..

**Comment by jfacorro** [comment]
@ramagandi I'm not sure I understand your question. A linux environment could also be a desktop environment. 

The `erlang_ls` extension can be installed following the docs [here](https://erlang-ls.github.io/editors/theia/).
