### ISSUE TITLE
erlang_ls appears to keep stale paths to an old OTP installation

### ISSUE THREAD

**Issue by kvelicka** [erlang-ls/erlang_ls#767]
**Describe the bug**
When trying to jump-to-definition of `gen_server:start_link` I get an error, which appears to occur due to a stale path cached somewhere.

**To Reproduce**
In my case, it happened after upgrading from OTP22 to OTP23 in Ubuntu

**Expected behavior**
Jump-to-definition should just work

**Actual behavior**
I get the following error

```
Unable to open 'gen_server.erl': Unable to read file 'vscode-remote://ssh-remote+$REDACTED_HOST/usr/lib/erlang/lib/stdlib-3.11.2/src/gen_server.erl' (Error: Unable to resolve non-existing file 'vscode-remote://ssh-remote+$REDACTED_HOST/usr/lib/erlang/lib/stdlib-3.11.2/src/gen_server.erl').
```

Looking at my paths, I see:
```
$ /usr/lib/erlang/lib/ | grep std
drwxr-xr-x  7 root root 4.0K Jun  4 09:47 stdlib-3.13
```

So `erlang_ls` appears to remember the old path from somewhere. I couldn't find the string `stdlib-3.11` in `~/.cache/erlang_ls` (aside from logs, same as above) so I'm not sure where it's being cached (or the data is stored in some binary format?).

Happy to provide further debug info if needed.

**Context**
 - `erlang_ls` version (tag/sha): 0.0.14 VSCode plugin (sha might be erlang_ls_2deaf158ff117f475d079be7b7559fed525e1625 based on the directory created in `~/.cache/erlang_ls`)
 - Editor used: VSCode
 - LSP client used: `erlang_ls` plugin

**Comment by ostrovsky** [comment]
I have a similar problem: jump-to-definition in erlang_ls built and running on erts-10.7.2.1 is trying to find a file in erts-10.5.5/src.

**Context**

- erlang_ls release 0.4.1 
- Emacs 26.3 with stable lsp packages

**Comment by robertoaloi** [comment]
Hi @kvelicka and @ostrovsky, sorry for the late reply. Information about OTP is cached, so I suggest you to kill the cache after an OTP upgrade. You can find the exact location of the cache by following the instructions at:

https://erlang-ls.github.io/internals/#the-erlang_ls-database

On a Linux system, it will be in `~/.cache/erlang_ls`. As you already guessed, the cache is stored in a binary format, which is why you cannot find occurrences of the string. Just wipe out that directory and restart the Language Server.

We should probably figure out a way to automatically do figure out stale paths, so I will leave this issue open.

**Comment by ostrovsky** [comment]
I did not upgrade OTP on the machine that experiences this issue.  However, I have build erlang_ls on a different machine with an older OTP release.  After your suggestion, I have rebuilt erlang_ls and cleared the cache.  It seems to work fine now.

**Comment by robertoaloi** [comment]
The latest version of Erlang LS does not persist OTP information across restarts, so this should not occur any longer.
