### ISSUE TITLE
Discussion : should we trash the db on startup?

### ISSUE THREAD

**Issue by alanz** [erlang-ls/erlang_ls#770]
At the moment, the startup process hangs while we wait for mnesia tables to be ready. For any decently sized code base, this wait can be quite long, in the order of minutes.

But we are now able to do indexing while the application is running, and index on-demand as a file is opened.  We also provide very clear feedback on the state of indexing vie `$/progress` messages.

So perhaps we will be better off just deleting the db on startup, so the IDE becomes responsive sooner, and the user can wait for indexing for full search capabilities.

Other possible alternatives are

a) use some other db instead of mnesia
b) use mnesia for core (small) information, and store the rest in files in the filesystem (perhaps using LSIF?).

`b)` is probably a very bad option, as it is basically rolling our own db.

**Comment by michalmuskala** [comment]
I wonder if using mnesia with disk-only tables could work. This would allow keeping the database only on disk and AFAIK should avoid the long loading to memory pause that is the issue. It will be a bit slower (since it means touching disk on every query), but I wouldn't expect it to be noticeable on the UI-scale times with a good db schema and OS-level file caching. This could potentially also solve high memory usage issues some users were complaining about.

A more complex solution could be to have a write-through cache in front of the database while it is initialising. On startup we'd start loading the main database and in parallel indexing as if there was no database to a purely in-memory store. Once the database is ready, it would be possible to merge the new information with the old and continue. This should avoid both - long initialisation because of loading the database and starting with a completely empty database every time.

**Comment by alanz** [comment]
My understanding is that the delay is while mnesia does an integrity check on the disk images before deciding to use them.  Using the on-disk vs in-ram is also something we could consider, but not directly relevant to this question.

**Comment by robertoaloi** [comment]
When I experimented with `disc_only_copies` the slowdown was evident (maybe there are still times around in my notes). But things changed a lot in the meantime, so it could be worth another try. I am not particularly attached to Mnesia as a DB, but it currently give us two things: a zero installation setup for the user and the possibility to store Erlang terms directly.

I also find the wait annoying, but It also seems that the wait is un-necessarily long. It's kind of insane for Mnesia to take such a long time to load tables into memory.

**Comment by alanz** [comment]
So `disc_only_copies` would speed it up?  Is it possible to have a blend, where some tables are ram, others disc only? We can possibly tune performance that way.  Or have more options in trading off startup vs performance.

We are also getting complaints about high RAM usage, which indicates disc copies.

**Comment by alanz** [comment]
From the [mnesia docs](https://erlang.org/doc/apps/mnesia/Mnesia_overview.html)

> Mnesia is not as appropriate with the following types of applications:
> ...
> - Applications that merely need a look-up dictionary that can be stored to disc. Those applications use the standard library module dets, which is a disc-based version of the module ets. For information about dets, see the dets manual page in STDLIB.

Would DETS be a better option?

**Comment by alanz** [comment]
Also, we are not running the db distributed, so maybe `mnesia:force_load_table(Tab)` is faster?

**Comment by robertoaloi** [comment]
Did you try it locally to see if there's any noticeable speedup? I would probably ping Richard on this. If there's room for optimizations in the way Mnesia is setup, he can probably figure out that very quickly and point us in the right direction.

**Comment by alanz** [comment]
ping @richcarl

**Comment by richcarl** [comment]
First, are you using transactions or QLC queries that make you prefer Mnesia over a plain naked DETS table?
Second, if it's normal disc_copies tables you're using, what are the sizes of these files for a project where it takes significant time to start mnesia? I've seen mnesia take many minutes to load a table, but that was for tables on the order of tens of GB.
Third, are the tables mostly read-only after being populated, or are they being constantly updated? DETS (or mnesia with disk_only_copies, which amounts to the same thing) is a plain hash table on disk; growing can be slow and there is no shrinking.

**Comment by alanz** [comment]
> are you using transactions or QLC queries

We are using a transaction to ensure that the update of the index for a given file is atoming.

> what are the sizes of these files for a project where it takes significant time to start mnesia? 

Around 1GB

> are the tables mostly read-only after being populated, or are they being constantly updated?

They capture the indexed info on the source code, so tend to get initially constructed and then not change much, an update on a file per save.

If they get too big, we can just trash them, it is only a cache.

**Comment by alanz** [comment]
And I have just checked, all the activities inside the transaction call `mnesia:dirty_write`.  Which as I understand it makes the transaction irrelevant?

Or does it affect reads?

**Comment by robertoaloi** [comment]
@richcarl 

All the Mnesia related code is in `els_db.erl`.

> First, are you using transactions or QLC queries that make you prefer Mnesia over a plain naked DETS table?

We use transactions during indexing (which can be parallelized), but that could be revisited. No QLC.
I believe in the old times we experimented with DETS and it was too slow for our needs. We can tolerate slow writing, since we mainly do that during the indexing process (which happens in the background when a project is first started), but we need fast access (we read a lot). Combining DETS + ETS would have meant re-inventing Mnesia and here we are. Of course right now we are paying the price for keeping (and loading) the entire DB in memory. This is not optimal for monolithic code bases, but works just fine for the Klarna code base, for example.

> Second, if it's normal disc_copies tables you're using, what are the sizes of these files for a project where it takes significant time to start mnesia?

Here you can find some data from my first experiments: https://github.com/erlang-ls/erlang_ls/issues/319

```
Code Base: 1.5 million lines of code

With empty tables it takes 400 ms to prepare tables.
Then it takes ~1m 40s to index the whole of OTP and the code base

With a Full DB, it takes ~25s to load tables and 10s to go through OTP and the same code base again, to figure out that everything is already indexed.

A Full DB means 4 tables:
Documents 600 MB
References 125 MB
Signatures 87 MB
Documents Index 1.2 MB

The table that takes the longest to load is the references table, which despite of the smaller size, has the biggest number of entries: 669.967
```

> Third, are the tables mostly read-only after being populated?

Yes.

**Comment by robertoaloi** [comment]
@alanz 

> And I have just checked, all the activities inside the transaction call mnesia:dirty_write. Which as I understand it makes the transaction irrelevant?

If I remember correctly, the reason why we introduced the transaction was to prevent a race condition between two indexing processes updating references.

**Comment by richcarl** [comment]
Dirty writes and reads, then it's a transaction in name only. Basically, if you don't have multiple processes that could be updating 2 or more entries concurrently, and no distribution of tables across nodes, then mnesia serves no purpose apart from not having to manage the file storage directly.

1 GB is at least a significant size, perhaps being worse if no "dump" has taken place after populating (then most of the table data is still in append-log form; a disc_copies table consists of a dump/snapshot plus a log of changes since latest dump). Dumps can be forced; perhaps worth checking if it makes a change. Also, you're not running on server grade hardware so I/O throughput can be expected to be less than what I've been used to. I'm not surprised if a gig takes a minute or so.

Keep in mind that dets is a 32-bit format - actually 31 because reasons - and when it reaches the 2GB limit it will corrupt silently, overwriting itself randomly. So that's basically a nope for a table already on the order of 1GB. And mnesia's disc_only_copies doesn't actually combine dets+ets - it only uses a dets table, with no caching whatsoever, not even the latest accessed key. Hence slow, and mainly useful as a way of stashing seldom accessed stuff. disc_copies on the other hand puts the whole table in an internal ets table (i.e. steals 1 GB of ram in this case) and just writes the change log to disk - on startup it must read the whole table from disk before it can be accessed - but after that it's quite fast :-)

I'd recommend trying to plug in Leveled (https://github.com/martinsumner/leveled) via the mnesia_leveled plugin (https://github.com/aeternity/mnesia_leveled). It's not LevelDB or RocksDB (you can try those if Leveled does not cut it), but it is battle proven as a store for Riak at NHS and has the advantage of being pure Erlang, no C bindings, so fully portable.

**Comment by robertoaloi** [comment]
> Dirty writes and reads, then it's a transaction in name only.

If that is the case, it should be considered a bug. Indexing is supposed to be performed by multiple processes, but I can see that in the current version we have one process indexing OTP, one indexing the project apps and one indexing the project deps. There should also be a ticket for allowing specifying a custom number of processes. My guess is that the current setup doesn't cause the bug to be evident in practice, but it should be fixed.

> perhaps being worse if no "dump" has taken place after populating

A dump is manually performed after indexing. This allowed us to save lot of time during the startup. I traced the waiting time and it's basically just the load-in-memory time which happens in Mnesia land. I even experimented with a branch which would load the table in parallel, but didn't notice any noticeable change.

> Keep in mind that dets is a 32-bit format - actually 31 because reasons - and when it reaches the 2GB limit it will corrupt silently, overwriting itself randomly.

I am aware. 1GB is for the monolithic WhatsApp code base, so it's not the "standard" case. I am happy to consider alternatives. My main constraints for a Mnesia replacement would be: simple encoding/decoding and, most important, minimal (zero) setup for the user.

> And mnesia's disc_only_copies doesn't actually combine dets+ets - it only uses a dets table, with no caching whatsoever, not even the latest accessed key.

We are using `disc_copies`, not `disc_only_copies`.

> I'd recommend trying to plug in Leveled (https://github.com/martinsumner/leveled) via the mnesia_leveled plugin (https://github.com/aeternity/mnesia_leveled). It's not LevelDB or RocksDB (you can try those if Leveled does not cut it), but it is battle proven as a store for Riak at NHS and has the advantage of being pure Erlang, no C bindings, so fully portable.

This would be a nice experiment. If anyone is willing to give it a try, I'm open.

**Comment by richcarl** [comment]
You could even try leveled without mnesia if you don't really need transactions.

**Comment by robertoaloi** [comment]
@richcarl @alanz I just tried to switch to Leveled as a DB. Unfortunately, `leveled` relies on the `lz4` NIF and that does not play well with escripts.

**Comment by alanz** [comment]
Pity.

**Comment by KennethL** [comment]
Would it not be good to try to rely on the DB features we already have in
OTP.
It is good to minimize the dependencies.
I am quite sure the current approach can be enhanced both performance and
memory wise by using ets and mnesia.
I am even open for adding features in OTP if that would make life easier.

/Kenneth

**Comment by alanz** [comment]
I actually think that mnesia itself is overkill for this use case, and we can perhaps move to dets only, or some such.

The main delay right now is waiting to load / check the tables on startup, which takes a few minutes for our code base, during which time the IDE is not available.

**Comment by KennethL** [comment]
On Mon, Sep 28, 2020, 17:56 Alan Zimmerman <notifications@github.com> wrote:

> I actually think that mnesia itself is overkill for this use case, and we
> can perhaps move to dets only, or some such.
>

yes thats what I meant, if you don't need support for transactions mnesia
is probably overkill. Ets and dets should be enough and give more
flexibility for optimizing speed and memory/disk usage.

> The main delay right now is waiting to load / check the tables on startup,
> which takes a few minutes for our code base, during which time the IDE is
> not available.
>

/Kenneth
