### ISSUE TITLE
Go to definition fails with functions that have a parametrised macro in their head.

### ISSUE THREAD

**Issue by aenglisc** [erlang-ls/erlang_ls#805]
**Describe the bug**
As per the title.

**To Reproduce**
Given the snippet below, the `hello/1` function throws a `Definition not found`, whereas the `hi/1` function is navigated to as expected, and so is `howdy/1`.
```
-module(erlang_ls_goto).

-export([hello/1]).
-export([hi/1]).
-export([howdy/1]).

-define(HELLO(World), {hello, World}).
-define(HOWDY, howdy).

hello(?HELLO(World)) ->
    World.

hi({hi, World}) ->
    World.

howdy(?HOWDY) ->
    howdy.

```

**Expected behaviour**
Go to definition should navigate to a function with a parametrised macro in its head.

**Actual behaviour**
`Definition not found`

**Context**
 - `erlang_ls` version (tag/sha): 0.5.0
 - Editor used: `nvim`
 - LSP client used: `coc.nvim`

**Comment by robertoaloi** [comment]
Thanks for reporting!

**Comment by robertoaloi** [comment]
So, the issue seems to be related to the `els_dodger` itself, which is a fork of the original `epp_dodger` in OTP. Also `epp_dodger` (and `ktn_dodger` for the records) seems to be affected. This can be reproduced by using your sample file:

```
> epp_dodger:parse_file("/path/to/erlang_ls_goto.erl").
{ok,[{tree,attribute,
           {attr,1,[],none},
           {attribute,{tree,atom,{attr,1,[],none},module},
                      [{tree,atom,{attr,1,[],none},erlang_ls_goto}]}},
     [...]
     {error,{10,erl_parse,["syntax error before: ","'('"]}},
     {tree,function,
           {attr,13,[],none},
     [...]
```

By redbugging the dodger, this is what happens:

```
% 14:58:42 <0.1305.0>({erlang,apply,2})
% epp_dodger:fix_form([{atom,10,hello},
 {'(',10},
 {'(',0},
 {atom,10,'? <macro> ('},
 {'(',10},
 {var,10,'HELLO'},
 {',',10},
 {var,10,'World'},
 {')',10},
 {')',0},
 {')',10},
 {'->',10},
 {var,11,'World'},
 {dot,11}])

% 14:58:42 <0.1305.0>({erlang,apply,2})
% epp_dodger:fix_form/1 -> error
```

The `fix_form` attempts at rescuing operations when "normal treatment" fails, but it's only tailored for `define`. We'd need to either implement another rescue procedure or understand why the first treatment fails in the first place.

I will ping the OTP team in case they want to look into this (it's probably faster for them).

Thanks @onno-vos-dev for helping pin-pointing the issue.

**Comment by robertoaloi** [comment]
Reported the bug upstream: https://bugs.erlang.org/browse/ERL-1429

**Comment by aenglisc** [comment]
Cool, thanks for the detailed response! Will try to dig into it too, looks like something to learn from
