### ISSUE TITLE
Suggested specs can be arbitrarily large

### ISSUE THREAD

**Issue by jesperes** [erlang-ls/erlang_ls#960]
**Describe the bug**

The `suggest-spec` code lense sometimes shows ridiculously long specs.

**To Reproduce**

For example:
![image](https://user-images.githubusercontent.com/310998/112949026-0c45da80-9139-11eb-9455-0e580504dd97.png)

**Expected behavior**
Code lens should not be several lines

**Actual behavior**
Code lens is 7 lines line, and could probably be arbitrarily large.

**Context**
 - `erlang_ls` version (tag/sha): 0.13.0
 - Editor used: Emacs
 - LSP client used: 20210328.1404

**Comment by robertoaloi** [comment]
Hi @jesperes !

The specs come directly from TypEr, so that's where we should look for improvements. TypEr, in its current form, is very simplistic. For example, one would like to see _aliases_ for the types which have been defined (not their bottom-line definition) and, for records, not to include all fields types. Some of this could be hard to implement. I know some people are looking at integrating Gradualizer as an alternative. Do you have any suggestion on how we could limit this (apart from obviously truncating the string)?

Ideas or contributions are welcome!

**Comment by hellmean** [comment]
is it possible not to print the full spec if it is longer than one line? And just truncate it and add "..." in the end? That way if somebody encounters such instances can still use the lens without it cluttering the editor. I guess, in the current state people who encounter this will be disabling this lens altogether, while it can still be useful most of the time.

**Comment by robertoaloi** [comment]
@hellmean That sounds like the easiest option for now. Fancy to give it a try?

**Comment by hellmean** [comment]
> @hellmean That sounds like the easiest option for now. Fancy to give it a try?

yep:) i was about to suggest that. Will open a [WIP] PR today/tomorrow.
